### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by comboshreddies** [comboshreddies/py-strace2pcap#5]
```
Traceback (most recent call last):
  File "/Users/milosprodanovic/GIT/py-strace2pcap/./py_strace2pcap.py", line 24, in <module>
    pktdump.write(packet)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/utils.py", line 1916, in write
    self.write_packet(p)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/utils.py", line 1841, in write_packet
    rawpkt = bytes_encode(packet)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/compat.py", line 303, in bytes_encode
    return bytes(x)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 589, in __bytes__
    return self.build()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 730, in build
    p = self.do_build()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 713, in do_build
    pay = self.do_build_payload()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 699, in do_build_payload
    return self.payload.do_build()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 713, in do_build
    pay = self.do_build_payload()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 699, in do_build_payload
    return self.payload.do_build()
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/packet.py", line 715, in do_build
    return self.post_build(pkt, pay)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/layers/inet.py", line 779, in post_build
    ck = in4_chksum(socket.IPPROTO_TCP, self.underlayer, p)
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/layers/inet.py", line 705, in in4_chksum
    psdhdr = in4_pseudoheader(proto, u, len(p))
  File "/Users/milosprodanovic/GIT/py-strace2pcap/venv/lib/python3.10/site-packages/scapy/layers/inet.py", line 687, in in4_pseudoheader
    return struct.pack("!4s4sHH",
struct.error: 'H' format requires 0 <= number <= 65535
```
=====

error comes from python struct.pack call

    return struct.pack("!4s4sHH",
                       inet_pton(socket.AF_INET, u.src),
                       inet_pton(socket.AF_INET, u.dst),
                       proto,
                       ln)

----
looks like there is specific payload that crashes use case

**Comment by comboshreddies** [comment]
payload of strace command might be bigger than 65535, tcp generic header can't keep that much data

**Comment by comboshreddies** [comment]
fixed in https://github.com/comboshreddies/py-strace2pcap/pull/7
